### ISSUE TITLE
smoke tests fail

### ISSUE THREAD

**Issue by rogpeppe** [tinygo-org/drivers#188]
commit 38f97a8b45d920716946a53943a04d56744bbc62

Ten of the "smoke tests" invoked by `make test` fail to compile for me.
Here are the errors that I see for the ones that fail:

```
tinygo build -size short -o ./build/test.hex -target=pybadge ./examples/amg88xx
# tinygo.org/x/drivers/examples/amg88xx
examples/amg88xx/main.go:16:22: SPI1_SDO_PIN not declared by package machine
examples/amg88xx/main.go:16:3: unknown field SDO in struct literal
examples/amg88xx/main.go:17:22: SPI1_SDI_PIN not declared by package machine
examples/amg88xx/main.go:17:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=itsybitsy-m0 ./examples/flash/console/spi
# tinygo.org/x/drivers/flash
flash/transport_spi.go:56:3: unknown field SDI in struct literal
flash/transport_spi.go:57:3: unknown field SDO in struct literal

tinygo build -size short -o ./build/test.hex -target=pyportal ./examples/flash/console/qspi
# tinygo.org/x/drivers/flash
flash/transport_spi.go:56:3: unknown field SDI in struct literal
flash/transport_spi.go:57:3: unknown field SDO in struct literal

tinygo build -size short -o ./build/test.hex -target=xiao ./examples/ili9341/basic
# tinygo.org/x/drivers/examples/ili9341/basic
examples/ili9341/basic/atsamd21.go:25:22: SPI0_SDO_PIN not declared by package machine
examples/ili9341/basic/atsamd21.go:25:3: unknown field SDO in struct literal
examples/ili9341/basic/atsamd21.go:26:22: SPI0_SDI_PIN not declared by package machine
examples/ili9341/basic/atsamd21.go:26:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=xiao ./examples/ili9341/scroll
# tinygo.org/x/drivers/examples/ili9341/scroll
examples/ili9341/scroll/atsamd21.go:25:22: SPI0_SDO_PIN not declared by package machine
examples/ili9341/scroll/atsamd21.go:25:3: unknown field SDO in struct literal
examples/ili9341/scroll/atsamd21.go:26:22: SPI0_SDI_PIN not declared by package machine
examples/ili9341/scroll/atsamd21.go:26:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=arduino-nano33 ./examples/wifinina/ntpclient/main.go
examples/wifinina/ntpclient/main.go:49:22: NINA_SDO not declared by package machine
examples/wifinina/ntpclient/main.go:49:3: unknown field SDO in struct literal
examples/wifinina/ntpclient/main.go:50:22: NINA_SDI not declared by package machine
examples/wifinina/ntpclient/main.go:50:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=arduino-nano33 ./examples/wifinina/udpstation/main.go
examples/wifinina/udpstation/main.go:46:22: NINA_SDO not declared by package machine
examples/wifinina/udpstation/main.go:46:3: unknown field SDO in struct literal
examples/wifinina/udpstation/main.go:47:22: NINA_SDI not declared by package machine
examples/wifinina/udpstation/main.go:47:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=arduino-nano33 ./examples/wifinina/tcpclient/main.go
examples/wifinina/tcpclient/main.go:58:22: NINA_SDO not declared by package machine
examples/wifinina/tcpclient/main.go:58:3: unknown field SDO in struct literal
examples/wifinina/tcpclient/main.go:59:22: NINA_SDI not declared by package machine
examples/wifinina/tcpclient/main.go:59:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=arduino-nano33 ./examples/wifinina/webclient/main.go
examples/wifinina/webclient/main.go:59:22: NINA_SDO not declared by package machine
examples/wifinina/webclient/main.go:59:3: unknown field SDO in struct literal
examples/wifinina/webclient/main.go:60:22: NINA_SDI not declared by package machine
examples/wifinina/webclient/main.go:60:3: unknown field SDI in struct literal

tinygo build -size short -o ./build/test.hex -target=digispark ./examples/ws2812
error: failed to build src/runtime/scheduler_avr.S: exec: "avr-gcc": executable file not found in $PATH
```

**Comment by deadprogram** [comment]
Looks like you are running version of TinyGo earlier than 0.14.0. Please update. This is likely due to https://github.com/tinygo-org/tinygo/pull/1216

**Comment by rogpeppe** [comment]
Sorry, somehow my version paste got erased when editing.
I'm using the tip version of tinygo, at commit 5714559923b9e2aeb133aee8738d4965f51cebfc:
```
% tinygo version
tinygo version 0.15.0-dev linux/amd64 (using go version go1.15 and LLVM version 10.0.1)
```

So I don't _think_ that that's the problem here.

**Comment by aykevl** [comment]
Pretty sure you're still using an older version somehow, or an older TinyGo root directory. You could try `tinygo clean`, which might fix it.

**Comment by sago35** [comment]
This problem occurs if avr-gcc is not installed.
A PR has been created to have the same response as the tinygo-org/tinygo Makefile.

**Comment by aykevl** [comment]
Ah, yes, that last error is indeed fixed by #189. The rest is the result of somehow using an older machine package.

**Comment by rogpeppe** [comment]
Where does tinygo look for the machine package? I've run a `make release` and am using the binary from the unpacked `release.tar.gz` file, but perhaps it's looking somewhere else. It does seem like it's finding the machine package somewhere else because I just verified that (for example) `machine.SPI1_SDO_PIN` is defined correctly when tag `pybadge` is set. How does the logic for finding the machine directory work?

**Comment by rogpeppe** [comment]
OK, I've found out (kinda) why this issue was happening. Somehow my `release` directory was "corrupted" (possibly by me untarring the release.tar.gz file there at some point in the past), and running `make release` did not fix the issue.

For the record:

```
$ find . -name board_pybadge.go  | xargs md5sum
e5892e49f9f3a481849ff6664105abdf  ./build/release/tinygo/src/machine/board_pybadge.go
7730d24a125d14abbf793ba124975293  ./build/release/tinygo/src/src/machine/board_pybadge.go
7730d24a125d14abbf793ba124975293  ./src/machine/board_pybadge.go
```

The result _should_ have been:
```
7730d24a125d14abbf793ba124975293  ./build/release/tinygo/src/machine/board_pybadge.go
7730d24a125d14abbf793ba124975293  ./src/machine/board_pybadge.go
```


Note the spurious `src/src` directory, which also showed up in the generated release.tar.gz file.
Weirdly, the 7730d24 version there is the correct version.
Perhaps there's a `cp -r` command in a script somewhere which isn't removing the target first?

I'll raise a new issue to track that problem and close this one.

**Comment by aykevl** [comment]
When something is messed up in the release directory, it's best to just run `make clean` to start over (which simply removes the build directory). From your previous comments, it wasn't clear to me what your setup was exactly.
Normally I don't build a release and extract that, instead I just copy over the `build/tinygo` file to somewhere in my `$PATH` and run that (for me, that's `~/bin`). It will remember the location it was built and deduce the source directory from that, making incremental changes easy.

**Comment by rogpeppe** [comment]
> When something is messed up in the release directory, it's best to just run make clean to start over (which simply removes the build directory).

I think that's a problem - I'd expect the build process to work regardless of the current state.
